/*
 * Stack Exchange API
 *
 * Stack Exchange API
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stackoverflow

type ReputationChange struct {
	OnDate           int32  `json:"on_date,omitempty"`
	ReputationChange int32  `json:"reputation_change,omitempty"`
	VoteType         string `json:"vote_type,omitempty"`
	PostType         string `json:"post_type,omitempty"`
	PostId           int32  `json:"post_id,omitempty"`
	UserId           int32  `json:"user_id,omitempty"`
}
