/*
 * Stack Exchange API
 *
 * Stack Exchange API
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stackexchange

type UserBadgeCounts struct {
	Bronze int32 `json:"bronze,omitempty"`
	Silver int32 `json:"silver,omitempty"`
	Gold   int32 `json:"gold,omitempty"`
}
