/*
 * Stack Exchange API
 *
 * Stack Exchange API
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stackexchange

type Question struct {
	Tags             []string      `json:"tags,omitempty"`
	Owner            QuestionOwner `json:"owner,omitempty"`
	IsAnswered       bool          `json:"is_answered,omitempty"`
	ViewCount        int32         `json:"view_count,omitempty"`
	AnswerCount      int32         `json:"answer_count,omitempty"`
	Score            int32         `json:"score,omitempty"`
	LastActivityDate int32         `json:"last_activity_date,omitempty"`
	CreationDate     int32         `json:"creation_date,omitempty"`
	QuestionId       int32         `json:"question_id,omitempty"`
	Link             string        `json:"link,omitempty"`
	Title            string        `json:"title,omitempty"`
}
