/*
 * Stack Exchange API
 *
 * Stack Exchange API
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stackoverflow

type ReputationHistory struct {
	ReputationHistoryType string `json:"reputation_history_type,omitempty"`
	ReputationChange      int32  `json:"reputation_change,omitempty"`
	PostId                int32  `json:"post_id,omitempty"`
	CreationDate          int32  `json:"creation_date,omitempty"`
	UserId                int32  `json:"user_id,omitempty"`
}
