/*
 * Stack Exchange API
 *
 * Stack Exchange API
 *
 * API version: 2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stackoverflow

type User struct {
	BadgeCounts             UserBadgeCounts `json:"badge_counts,omitempty"`
	AboutMe                 string          `json:"about_me,omitempty"`
	AccountId               int64           `json:"account_id,omitempty"`
	IsEmployee              bool            `json:"is_employee,omitempty"`
	LastModifiedDate        int64           `json:"last_modified_date,omitempty"`
	LastAccessDate          int64           `json:"last_access_date,omitempty"`
	ReputationChangeYear    int32           `json:"reputation_change_year,omitempty"`
	ReputationChangeQuarter int32           `json:"reputation_change_quarter,omitempty"`
	ReputationChangeMonth   int32           `json:"reputation_change_month,omitempty"`
	ReputationChangeWeek    int32           `json:"reputation_change_week,omitempty"`
	ReputationChangeDay     int32           `json:"reputation_change_day,omitempty"`
	Reputation              int64           `json:"reputation,omitempty"`
	CreationDate            int64           `json:"creation_date,omitempty"`
	UserType                string          `json:"user_type,omitempty"`
	UserId                  int64           `json:"user_id,omitempty"`
	AcceptRate              int32           `json:"accept_rate,omitempty"`
	Location                string          `json:"location,omitempty"`
	WebsiteUrl              string          `json:"website_url,omitempty"`
	Link                    string          `json:"link,omitempty"`
	ProfileImage            string          `json:"profile_image,omitempty"`
	DisplayName             string          `json:"display_name,omitempty"`
}
